### ISSUE TITLE
Reslate not found on npm registry

### ISSUE THREAD

**Issue by Rocket-Fish** [Mermade/reslate#19]
**Bug Description**
`npm i reslate` and `npx reslate init` both does not work. misleading install instructions on readme.md? 

**Screenshots**
```
$ npm i reslate
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/reslate - Not found
npm ERR! 404 
npm ERR! 404  'reslate@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```

```
$ npx reslate init
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/reslate - Not found
npm ERR! 404 
npm ERR! 404  'reslate@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```
also [https://www.npmjs.com/search?q=reslate](https://www.npmjs.com/search?q=reslate) 
yields 0 packages found
<img width="1294" alt="Screen Shot 2020-11-10 at 1 24 36 PM" src="https://user-images.githubusercontent.com/14224576/98715412-1b79e680-2358-11eb-8aca-8522a55d43c0.png">

**Browser (please complete the following information):**
 - OS: Any
 - Browser Node
 - Version 10.22.1

**Last upstream Slate commit (run `git log --author="Robert Lord" | head -n 1`):**
a8a65b0752af7c3e5e25b9fdbf4cddfd23c72749

**Comment by MikeRalphson** [comment]
Yes, it hasn't been published yet. The instructions have to be written first otherwise they won't be present on npm.

**Comment by Rocket-Fish** [comment]
sounds good, i just wanted to bring this to attention just in case this was a bug or something unintentional.

**Comment by MikeRalphson** [comment]
Thanks! Will close this when published.

**Comment by MikeRalphson** [comment]
Now up to date and published.
