### ISSUE TITLE
Lack of copy.js breaks language selection

### ISSUE THREAD

**Issue by monkeysppp** [Mermade/reslate#28]
**Bug Description**
I think the fix in 3.0.0-2 (https://github.com/Mermade/reslate/commit/ea8371ca8e877e9fa2b01a9ecfb2eb533e36bb96) has revealed/triggered a bug whereby the language selection tabs don't trigger the example code to switch.

I don't have `code_clipboard` defined in my starting Markdown; that's just what was generated by `widdershins`, which doesn't seem to define `code_clipboard` (the word "code_clipboard" doesn't appear [anywhere in their repo](https://github.com/Mermade/widdershins/search?q=code_clipboard))

This results in `slate/js/app/copy.js` not being included in the `index.html`.  That then results in the following error to the console:

```
jQuery.Deferred exception: setupCodeCopy is not defined setupLanguages@file:///C:/Users/andy/workspace/gitea/Proj/proj-api-docs/_site/slate/js/app/lang.js line 37 > srcScript:150:9
@file:///C:/Users/andy/workspace/gitea/Proj/proj-api-docs/_site/index.html?javascript#getitems line 37 > inlineScript:29:23
e@file:///C:/Users/andy/workspace/gitea/Proj/proj-api-docs/_site/slate/js/lib/jquery.min.js line 37 > srcScript:2:30005
l/</t<@file:///C:/Users/andy/workspace/gitea/Proj/proj-api-docs/_site/slate/js/lib/jquery.min.js line 37 > srcScript:2:30307
activateLanguage@file:///C:/Users/andy/workspace/gitea/Proj/proj-api-docs/_site/slate/js/app/lang.js:37:5
@file:///C:/Users/andy/workspace/gitea/Proj/proj-api-docs/_site/slate/js/app/lang.js:176:23
dispatch@file:///C:/Users/andy/workspace/gitea/Proj/proj-api-docs/_site/slate/js/lib/jquery.min.js:2:43090
add/v.handle@file:///C:/Users/andy/workspace/gitea/Proj/proj-api-docs/_site/slate/js/lib/jquery.min.js:2:41074
---
Uncaught ReferenceError: setupCodeCopy is not defined
    setupLanguages file:///C:/Users/andy/workspace/gitea/Proj/proj-api-docs/_site/slate/js/app/lang.js line 37 > srcScript:150
    <anonymous> file:///C:/Users/andy/workspace/gitea/Proj/proj-api-docs/_site/index.html?javascript#getmachines line 37 > inlineScript:29
    jQuery 2
    activateLanguage file:///C:/Users/andy/workspace/gitea/Proj/proj-api-docs/_site/slate/js/app/lang.js:37
    <anonymous> file:///C:/Users/andy/workspace/gitea/Proj/proj-api-docs/_site/slate/js/app/lang.js:176
    jQuery 2
```

So `setupLanguages` requires code from `copy.js`, that isn't there if you don't explicitly define and set `code_clipboard` to true.

Note that I'm also hitting #25, so I've had to implemented workarounds to get past that - basically copying in the missing .js files.

**Screenshots**

"Shell" highlighted, only that isn't the shell code:

![image](https://user-images.githubusercontent.com/510109/103173993-6f805200-4856-11eb-8029-131abeb40bb5.png)

"Python" highlighted, but it's the same sample code:
![image](https://user-images.githubusercontent.com/510109/103173999-7c9d4100-4856-11eb-91e5-f19adbacdc6d.png)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefix / Chrome
 - Version: 84.0.1 / 

**Last upstream Slate commit (run `git log --author="Robert Lord" | head -n 1`):**
This is using `3.0.0-2`

**Comment by MikeRalphson** [comment]
This should be fixed in `reslate@3.0.0-3` - thanks for the report.

Nb: the `code_clipboard` option is a new feature of Slate/ReSlate since the last Widdershins release. It will be supported in the next one.
